import React, { useState, useEffect } from 'react';
import { Activity, Cpu, Database, Eye, CheckCircle2, AlertTriangle, RefreshCw, Zap, Radio } from 'lucide-react';
import { fetchPipelineHealth } from '../services/api';

export const PipelineHealthView: React.FC = () => {
  const [healthData, setHealthData] = useState<any>(null);
  const [loading, setLoading] = useState(false);

  const loadHealth = async () => {
    setLoading(true);
    try {
      const data = await fetchPipelineHealth();
      setHealthData(data);
    } catch (e) {
      console.error('Error fetching pipeline health:', e);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadHealth();
    const interval = setInterval(loadHealth, 3000);
    return () => clearInterval(interval);
  }, []);

  return (
    <div className="p-6 space-y-6">
      <div className="glass-panel rounded-2xl p-6 border border-cyan-900/60 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2 text-cyan-400 font-mono text-xs uppercase tracking-wider font-semibold">
            <Activity className="w-4 h-4 text-cyan-400" />
            <span>2-Stage ANPR Stream Health & Operational Telemetry</span>
          </div>
          <h2 className="text-xl font-bold text-white mt-1">Real-Time Video & ANPR Pipeline Diagnostics</h2>
        </div>

        <button
          onClick={loadHealth}
          className="bg-cyan-950 border border-cyan-800 hover:border-cyan-400 text-cyan-400 text-xs font-mono px-4 py-2 rounded-xl flex items-center gap-2 transition-all"
        >
          <RefreshCw className={`w-3.5 h-3.5 ${loading ? 'animate-spin' : ''}`} />
          <span>REFRESH TELEMETRY</span>
        </button>
      </div>

      {healthData && (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
          <div className="glass-panel rounded-2xl p-5 border border-emerald-900/60">
            <div className="text-xs font-mono text-slate-400 uppercase">Processing Mode</div>
            <div className="text-lg font-extrabold font-mono text-emerald-400 mt-1">{healthData.processing_mode}</div>
            <div className="text-[11px] text-slate-400 font-mono mt-1">Uptime: {healthData.uptime_seconds}s</div>
          </div>

          <div className="glass-panel rounded-2xl p-5 border border-cyan-900/60">
            <div className="text-xs font-mono text-slate-400 uppercase">Stream Status & FPS</div>
            <div className="text-2xl font-extrabold font-mono text-cyan-400 mt-1">{healthData.pipeline_fps} FPS</div>
            <div className="text-[11px] text-cyan-300 font-mono mt-1">{healthData.active_streams} Active Worker Streams</div>
          </div>

          <div className="glass-panel rounded-2xl p-5 border border-blue-900/60">
            <div className="text-xs font-mono text-slate-400 uppercase">YOLO Inference Latency</div>
            <div className="text-2xl font-extrabold font-mono text-blue-400 mt-1">{healthData.yolo_inference_ms} ms</div>
            <div className="text-[11px] text-slate-400 font-mono mt-1">{healthData.frames_processed} Frames Processed</div>
          </div>

          <div className="glass-panel rounded-2xl p-5 border border-purple-900/60">
            <div className="text-xs font-mono text-slate-400 uppercase">OCR Valid Plate Rate</div>
            <div className="text-2xl font-extrabold font-mono text-purple-400 mt-1">{healthData.ocr_valid_plate_rate}%</div>
            <div className="text-[11px] text-purple-300 font-mono mt-1">{healthData.db_inserts} DB Rows Inserted</div>
          </div>
        </div>
      )}

      {/* Operational ANPR Telemetry Table */}
      {healthData && (
        <div className="glass-panel rounded-2xl p-5 border border-cyan-900/80 space-y-4">
          <h3 className="text-sm font-mono font-bold text-cyan-400 uppercase tracking-wider flex items-center gap-2">
            <Cpu className="w-4 h-4 text-cyan-400" />
            <span>2-Stage ANPR Operational Quality Metrics</span>
          </h3>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-xs font-mono">
            <div className="bg-[#0f172a] border border-cyan-950 p-4 rounded-xl space-y-2">
              <div className="flex justify-between border-b border-cyan-950 pb-1">
                <span className="text-slate-400">Total Frames Received from StreamManager:</span>
                <span className="text-white font-bold">{healthData.frames_received}</span>
              </div>
              <div className="flex justify-between border-b border-cyan-950 pb-1">
                <span className="text-slate-400">Total Detections Generated by YOLO:</span>
                <span className="text-cyan-400 font-bold">{healthData.detections_generated}</span>
              </div>
              <div className="flex justify-between">
                <span className="text-slate-400">Errors & RTSP Reconnections:</span>
                <span className="text-rose-400 font-bold">{healthData.reconnects_and_errors}</span>
              </div>
            </div>

            <div className="bg-[#0f172a] border border-cyan-950 p-4 rounded-xl space-y-2">
              <div className="flex justify-between border-b border-cyan-950 pb-1">
                <span className="text-slate-400">ANPR OCR Attempts:</span>
                <span className="text-white font-bold">{healthData.ocr_attempts}</span>
              </div>
              <div className="flex justify-between border-b border-cyan-950 pb-1">
                <span className="text-slate-400">OCR Valid Indian Plates Recognized:</span>
                <span className="text-emerald-400 font-bold">{healthData.ocr_valid_plates}</span>
              </div>
              <div className="flex justify-between border-b border-cyan-950 pb-1">
                <span className="text-slate-400">OCR Average Confidence:</span>
                <span className="text-sky-400 font-bold">{healthData.ocr_avg_confidence}%</span>
              </div>
              <div className="flex justify-between">
                <span className="text-slate-400">Database Inserts (PostGIS):</span>
                <span className="text-purple-400 font-bold">{healthData.db_inserts}</span>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
